"""Описание изменений

Revision ID: 36ed3b2fec1c
Revises: 
Create Date: 2026-01-08 21:48:51.302619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ed3b2fec1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер достижения'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Название достижения'),
    sa.Column('desc', sa.String(length=250), nullable=False, comment='Описание достижения'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер записи'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='Код верификации'),
    sa.Column('email', sa.String(), nullable=False, comment='Электронная почта пользователя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codes_id'), 'codes', ['id'], unique=False)
    op.create_table('game_history',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер истории игроков'),
    sa.Column('players', sa.JSON(), nullable=False, comment='Игроки'),
    sa.Column('game_name', sa.String(), nullable=False, comment='Название игры'),
    sa.Column('game_id', sa.Integer(), nullable=False, comment='Номер игры'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_history_id'), 'game_history', ['id'], unique=False)
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер ранга'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Название ранга'),
    sa.Column('points_required', sa.Integer(), nullable=False, comment='Количество очков для ранга'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranks_id'), 'ranks', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название комнаты'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='Приватная'),
    sa.Column('password', sa.String(length=50), nullable=True, comment='Пароль'),
    sa.Column('game_name', sa.String(), nullable=False, comment='Название игры'),
    sa.Column('max_players', sa.Integer(), nullable=False, comment='Максимальное количество игроков'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания лобби'),
    sa.Column('afk_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время простоя лобби'),
    sa.Column('started', sa.Boolean(), nullable=False, comment='Игра началась'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False, comment='Id записи'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Номер пользователя'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Номер комнаты'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер игрока'),
    sa.Column('name', sa.String(), nullable=False, comment='Ник игрока'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Номер пользователя'),
    sa.Column('is_disconnect', sa.Boolean(), nullable=False, comment='Разрыв соединения'),
    sa.Column('nickname_color', sa.String(length=8), nullable=False, comment='Цвет ника'),
    sa.Column('avatar', sa.String(), nullable=True, comment='Путь к аватару'),
    sa.Column('is_vip', sa.Boolean(), nullable=False, comment='VIP статус'),
    sa.Column('is_host', sa.Boolean(), nullable=False, comment='Хост'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ID комнаты, в которой находится игрок'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер пользователя'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Имя пользователя'),
    sa.Column('email', sa.String(), nullable=True, comment='Электронная почта'),
    sa.Column('hash_password', sa.String(length=120), nullable=True, comment='Хешированный пароль'),
    sa.Column('exp', sa.Integer(), nullable=False, comment='Очки опыта'),
    sa.Column('rank_id', sa.Integer(), nullable=True, comment='Номер ранга'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Статус пользователя'),
    sa.Column('date_joined', sa.DateTime(), nullable=False, comment='Дата регистрации'),
    sa.Column('avatar', sa.String(), nullable=True, comment='Путь к аватару'),
    sa.Column('is_vip', sa.Boolean(), nullable=False, comment='VIP статус'),
    sa.Column('its_vip_time', sa.DateTime(), nullable=True, comment='Дата получения VIP статуса'),
    sa.Column('count_vip_card_reset', sa.Integer(), nullable=False, comment='Количество сбросов карт VIP'),
    sa.Column('dracoins', sa.Integer(), nullable=True, comment='Дракоины пользователя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активность пользователя'),
    sa.Column('in_room', sa.Boolean(), nullable=False, comment='Присутствие в комнате'),
    sa.Column('nickname_color', sa.String(length=8), nullable=False, comment='Цвет ника'),
    sa.Column('time_last_game', sa.DateTime(timezone=True), nullable=False, comment='Время последней игры'),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('game_achievements',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер достижения игрока'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Номер игрока'),
    sa.Column('achievement_id', sa.Integer(), nullable=False, comment='Номер достижения'),
    sa.Column('game_name', sa.String(), nullable=False, comment='Название игры'),
    sa.Column('receiving_cond', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время получения'),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_achievements_id'), 'game_achievements', ['id'], unique=False)
    op.create_table('player_game_statistics',
    sa.Column('id', sa.Integer(), nullable=False, comment='Номер записи'),
    sa.Column('game_name', sa.String(), nullable=False, comment='Название игры'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Номер игрока'),
    sa.Column('total_game', sa.Integer(), nullable=False, comment='Сколько игр сыгранно'),
    sa.Column('won_game', sa.Integer(), nullable=False, comment='Сколько игр выиграно'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_statistics_id'), 'player_game_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_game_statistics_id'), table_name='player_game_statistics')
    op.drop_table('player_game_statistics')
    op.drop_index(op.f('ix_game_achievements_id'), table_name='game_achievements')
    op.drop_table('game_achievements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_ranks_id'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_game_history_id'), table_name='game_history')
    op.drop_table('game_history')
    op.drop_index(op.f('ix_codes_id'), table_name='codes')
    op.drop_table('codes')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
